[package]
name = "nzsc_single_player_cli"
version = "0.2.0"
authors = ["Kyle Lin <kylejlin.us@gmail.com>"]

repository = "https://github.com/kylejlin/nzsc_single_player_cli"

license = "MIT"

[dependencies]
nzsc_single_player = "0.1.0"
