[package]
name = "nzsc_single_player_cli"
version = "0.4.2"
authors = ["Kyle Lin <kylejlin.us@gmail.com>"]

repository = "https://github.com/nzsc-org/nzsc_single_player_cli"

license = "MIT"

[dependencies]
nzsc_single_player = "0.4.4"
rand = "0.3.14"
