[package]
name = "nzsc_single_player_cli"
version = "0.5.3"
authors = ["Kyle Lin <kylejlin.us@gmail.com>"]

repository = "https://github.com/nzsc-org/nzsc_single_player_cli"

license = "MIT"

[dependencies]
nzsc_single_player = "0.5.1"
nzsc_single_player_text_interface = "0.2.2"
rand = "0.3.14"
